name: PyBayesian

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:

  buildx:

    runs-on: ubuntu-latest
    env:
      NAME_VERSION: pybayesian:2024v1
    steps:
    # 1 check
    - name: Checkout
      uses: actions/checkout@v4
    # 2 log in
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # 3 set up
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: push amd64
      run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.NAME_VERSION}}-amd64 -f Dockerfile . --push
    - name: push arm64
      run: docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.NAME_VERSION}}-arm64 -f Dockerfile . --push
    - name: Build the Combined Manifest
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.NAME_VERSION}} -f Dockerfile . --push
    - name: Build the Newest Manifest
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/pybayesian:latest -f Dockerfile . --push