name: PyBayesian

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildx:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pybayesian
      VERSION: 2024v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push amd64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-amd64 \
            -f Dockerfile . \
            --push

      - name: Push arm64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-arm64 \
            -f Dockerfile . \
            --push

      - name: Build the Combined Manifest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            -f Dockerfile . \
            --push

      - name: Build the Latest Manifest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            -f Dockerfile . \
            --push